{{- if .Values.backup_before_update }}
apiVersion: batch/v1
kind: Job
metadata:
  name: database-backup
spec:
  template:
    spec:
      containers:
        - name: database-backup
          image: {{ if eq .Values.container_registry "Aliyun" }}registry.cn-beijing.aliyuncs.com/{{ end }}baijunyao/mysql-client:1.1
          command: ["/bin/sh", "-c", "/usr/bin/mysqldump -hmysql-service -uroot -p{{ .Values.mysql.password }} laravel_bjyblog | gzip > /backup/laravel_bjyblog_`date +%Y%m%d`.sql.gz"]
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          volumeMounts:
            - mountPath: /backup
              name: backup-pvc
              subPath: database
      volumes:
        - name: backup-pvc
          persistentVolumeClaim:
            claimName: backup-pvc
      restartPolicy: Never

---
{{- end }}

{{- if .Values.backup_before_update }}
apiVersion: batch/v1
kind: Job
metadata:
  name: database-backup
spec:
  template:
    spec:
      containers:
        - name: site-backup
          image: {{ if eq .Values.container_registry "Aliyun" }}registry.cn-beijing.aliyuncs.com/{{ end }}baijunyao/alpine:3.12
          command: ["/bin/sh", "-c", "/bin/tar -czvf /backup/laravel_bjyblog_`date +%Y%m%d`.tar.gz /app/.env /app/storage/app/public/uploads"]
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          volumeMounts:
            - mountPath: /backup
              name: backup-pvc
              subPath: site
            - mountPath: /app
              name: code-pvc
      volumes:
        - name: backup-pvc
          persistentVolumeClaim:
            claimName: backup-pvc
        - name: code-pvc
          persistentVolumeClaim:
            claimName: code-pvc
      restartPolicy: Never

{{- end }}
